### ISSUE TITLE
Fix Western Traps

### ISSUE THREAD

**Issue by Danghorx** [legacyclonk/content#10] opened 2022-08-06 13:23 UTC
~~This error comes, in western, when you play and the clonk cant do a command. It happend at the start when you chop wood in Milestone Woods.
WARNING: call to "ControlCommandFinished" parameter 3: got "id", but expected "int"! (obj Jim #1118)~~

In Milestone Woods the traps where you can get the chalice dont work you just walk over them. It worked in CR 330.

**Comment by Fulgen301** [comment] 2022-08-06 18:10
> This error

This is a warning, not an error.

**Comment by maxmitti** [comment] 2022-12-08 11:52
> It worked in CR 330.

I just checked in http://www.clonkx.de/rage/cr_western.zip and it definitely does not work in that version either, regardless which engine is used.
The problem is, that the traps need to be in an appropriate `Action` to function, but in `Objects.txt` the `Action` is either not present (`Idle`) or wrong.
To me it seems like the scenarios were created when traps were implemented differently and never updated to work with the current version.

I have also found that Last Hope is also affected.

**Closed as completed** 2022-12-08 11:57 UTC
